name: Publish a IDEA plugin release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta[0-9]+-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta[0-9]+-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC[0-9]+-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC[0-9]+-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta[0-9]+-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-Beta[0-9]+-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC[0-9]+-idea-[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ALPHA-[0-9]+-kotlin-[0-9]+.[0-9]+.[0-9]+-RC[0-9]+-idea-[0-9]+.[0-9]+-EAP-[0-9]+.[0-9]+'
env:
  JAVA_VERSION: '17'
jobs:
  publish-idea-plugin:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Publish IDEA plugin
        run: ./gradlew publishPlugin
        env:
          IDEA_CERTIFICATE_CHAIN: ${{ secrets.IDEA_CERTIFICATE_CHAIN }}
          IDEA_PRIVATE_KEY: ${{ secrets.IDEA_PRIVATE_KEY }}
          IDEA_PRIVATE_KEY_PASSWORD: ${{ secrets.IDEA_PRIVATE_KEY_PASSWORD }}
          IDEA_PUBLISH_TOKEN: ${{ secrets.IDEA_PUBLISH_TOKEN }}
